### ISSUE TITLE
TODO: 一些想分享的主題?

### ISSUE THREAD

**Issue by jcs090218** [jcs090218/blog#10]
這裡用來放我想到, 並且可以分享的主題!~

- [x] Fastest ELPA in the world?
- [ ] 分享 `company-fuzzy`, 看[這](https://emacs-china.org/t/topic/3905/13)
- [x] How to build your own ELPA with Eask?
- [ ] Publish Eask CLI to multiple package managers
- [x] Create Elisp language server ([ellsp](https://github.com/jcs090218/ellsp))

歡迎其他人在此串留言~
